name: PR Dependency Check

on:
  pull_request:
    paths:
      - '**/*.xml'

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for accurate diff
        ref: ${{ github.event.pull_request.head.sha }} # Ensure correct PR head is checked out

    - name: Fetch base branch
      run: |
        # Fetch the base branch (target branch of the PR)
        git fetch origin $GITHUB_BASE_REF
        git checkout $GITHUB_BASE_REF

    - name: Fetch list of changed files
      id: changed-files
      run: |
        # Get list of changed files in the PR
        CHANGED_FILES=$(git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_HEAD_REF)
        echo "$CHANGED_FILES" > changed_files.txt
        echo "Changed files:"
        cat changed_files.txt

    - name: Check for dependent files
      id: dependency-check
      run: |
        # Read the list of changed files
        CHANGED_FILES=$(cat changed_files.txt)

        # Initialize failure flag
        FAIL=false

        # Loop through changed files and check for dependencies
        for FILE in $CHANGED_FILES; do
          if [[ "$FILE" =~ ^src/a_.*\.xml$ ]]; then
            DEPENDENT_FILE="${FILE/a_/a_dependent_}"
            if ! echo "$CHANGED_FILES" | grep -q "$DEPENDENT_FILE"; then
              echo "Error: Missing dependent file for $FILE. Expected: $DEPENDENT_FILE"
              FAIL=true
            fi
          fi
        done

        # Fail the step if any dependency is missing
        if $FAIL; then
          exit 1
        fi
      shell: bash
